export const openPlaces = [
  {
    id: 1,
    type: "bistro",
    name: "На Маховій",
    address: "Вулиця Олександра Махова, 4",
    img: "/images/comingPlaces/img8.webp",
    href: "https://maps.app.goo.gl/iVqtcDfwxtdsXNCp6",
  },
  {
    id: 2,
    type: "bistro",
    name: "На Лятошинського",
    address: "Вулиця Лятошинського, 14",
    img: "/images/comingPlaces/img11.webp",
    href: "https://maps.app.goo.gl/L4bNx5cGcvcTvmyo9",
  },
  {
    id: 3,
    type: "bistro",
    name: "На Щербаківського",
    address: "Вулиця Данила Щербаківського, 52",
    img: "/images/comingPlaces/img12.webp",
    href: "https://maps.app.goo.gl/FRf1LoWchEqxHu4Q7",
  },
  {
    id: 4,
    type: "bistro",
    name: "На Бажана",
    address: "Проспект Миколи Бажана, 3",
    img: "/images/comingPlaces/img10.webp",
    href: "https://maps.app.goo.gl/RbMbjZUcFe4P8wmJ6",
  },
  {
    id: 5,
    type: "bistro",
    name: "На Академ",
    address: "Вулиця Чорнобильська, 16/80",
    img: "/images/comingPlaces/img13.webp",
    href: "https://maps.app.goo.gl/xXKRLGAwveexN4EZ6",
  },
  {
    id: 6,
    type: "bistro",
    name: "На КПІ",
    address: "Політехнічний провулок, 6",
    img: "/images/comingPlaces/img14.jpeg",
    href: "https://maps.app.goo.gl/orzE9aymyJoo3fbu5",
  },
  {
    id: 7,
    type: "foodcourt",
    name: "ТРЦ Глобус",
    address: "Майдан Незалежності, 1",
    img: "/images/comingPlaces/img9.webp",
    href: "https://maps.app.goo.gl/BsvuSK3ATaoCnQRF9",
  },
  {
    id: 8,
    type: "restaurant",
    name: "На Повітряних Сил",
    address: "Проспект Повітряних Сил, 25",
    img: "/images/comingPlaces/img7.webp",
    href: "https://maps.app.goo.gl/jHTTCoPjncyHtawA7",
  },
  {
    id: 9,
    type: "restaurant",
    name: "На Оболонській набережній",
    address: "Вулиця Оболонська набережна, 11",
    img: "/images/comingPlaces/img5.webp",
    href: "https://maps.app.goo.gl/pvjUKUUpYS1UU9PN7",
  },
  {
    id: 10,
    type: "restaurant",
    name: "На Здановській",
    address: "Вулиця Юлії Здановської, 62/5",
    img: "/images/comingPlaces/img15.webp",
    href: "https://maps.app.goo.gl/dE48WeuhiT2XvNaM8",
  },
  {
    id: 11,
    type: "restaurant",
    name: "На Крістерів",
    address: "Вулиця Родини Крістерів, 20",
    img: "/images/comingPlaces/img6.webp",
    href: "https://maps.app.goo.gl/Hpd5JVURhbJmAVPX7",
  },
];
